# Generated by Django 5.2.8 on 2025-12-03 11:33

import django.db.models.deletion
import recetasapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetasapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaIngredientes',
            new_name='CategoriaIngrediente',
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='medida',
            field=models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilogramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('u', 'Unidad')], default='g', max_length=5),
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='refrigerado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredientes',
            name='nombre',
            field=models.CharField(max_length=50, validators=[recetasapp.models.validate_nombre]),
        ),
        migrations.CreateModel(
            name='IngredienteReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('unidad_medida', models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilogramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('u', 'Unidad')], max_length=2)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetasapp.ingredientes')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('ingredientes', models.ManyToManyField(related_name='recetas', through='recetasapp.IngredienteReceta', to='recetasapp.ingredientes')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientereceta',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetasapp.receta'),
        ),
    ]
