# Generated by Django 5.2.8 on 2025-11-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetasapp', '0002_rename_categoriaingredientes_categoriaingrediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientes',
            name='refrigerado',
            field=models.BooleanField(default=False),
        ),
    ]
