# Generated by Django 5.2.8 on 2025-12-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetasapp', '0002_rename_categoriaingredientes_categoriaingrediente_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientereceta',
            unique_together={('receta', 'ingrediente')},
        ),
    ]
