# Generated by Django 5.2.8 on 2025-11-27 10:29

import recetasapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetasapp', '0003_ingredientes_refrigerado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientes',
            name='medida',
            field=models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilogramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('u', 'Unidad')], default='g', max_length=5),
        ),
        migrations.AlterField(
            model_name='ingredientes',
            name='nombre',
            field=models.CharField(max_length=50, validators=[recetasapp.models.validate_nombre]),
        ),
    ]
