# Generated by Django 5.2.8 on 2025-12-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetasapp', '0004_ingredientes_medida_alter_ingredientes_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('ingredientes', models.ManyToManyField(to='recetasapp.ingredientes')),
            ],
        ),
    ]
