# Generated by Django 5.2.8 on 2025-12-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetasapp', '0005_receta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='ingredientes',
            field=models.ManyToManyField(related_name='recetas', to='recetasapp.ingredientes'),
        ),
    ]
